### ISSUE TITLE
Video freezings

### ISSUE THREAD

**Issue by Ooow6** [sstativa/mfc-node#42] opened 2017-10-29 19:38 UTC
Hello @sstativa Will you fix an issue with video recording? Something wrong and now videos are freezings.

Is it possible to fix?

**Comment by sstativa** [comment] 2017-10-29 23:52
This is not a script related issue, the HLS streams from MFC are "broken" therefore you have the issue. There is no way to fix it this unless you switch to recording RTMP streams. 

I already have a version of the script that can record both types of streams (HLS and RTMP) and I can confirm that RTMP streams have no freezing issues. However, I'm bit reluctant to make that version public unless I get some donations. I've already mentioned following once, I'll repeat it  again: 

> Let's do it this way, if one day I rich the goal in 333 coffees, I'll release my private version of the script with rtmpdump support.
> 
> You could say that I got greedy and probably you are right, but the lack of support discourages me from doing anything else with the script. Ffmpeg version still does a pretty good job.

**Comment by Ooow6** [comment] 2017-10-30 06:13
@sstativa Is it possible to buy it for private usage? Can i contact you via email ?

**Comment by sstativa** [comment] 2017-10-30 08:26
My guess will be that this "broke" is just a temporary issue.

As for buying, I would rather prefer "crowd funding" style because there is no way to control the code, someone will "leak" it soon or later. 

However, buy me a coffee (quantity at your discretion) and I'll figure out something for you. I assume you are Windows user, am I right?

**Comment by Ooow6** [comment] 2017-10-30 15:02
@sstativa , yes i'm Windows user

lmk what's the minimum you would wish to get coffee from me?

**Comment by Ooow6** [comment] 2017-10-30 17:33
p.s. about "crowd funding" i wish it would be possible, but there are no comments here and on any forum to reach this coffee goal. That's bad

**Comment by Hampster82** [comment] 2017-10-30 20:29
I also noticed that mfc's hls streams have been garbage lately, surprised that it doesn't seem like a lot of people are complaining though, I guess their mobile userbase is still small enough.

If I were to buy you coffee, how would you go about verifying that it was me? Never used ko-fi before.

**Comment by Ooow6** [comment] 2017-10-30 21:45
> I also noticed that mfc's hls streams have been garbage lately
And how long did it take the previous time?

**Comment by Hampster82** [comment] 2017-10-31 00:55
I don't remember a previous time, this is the first one for me since I started using hls cappers.

**Comment by sstativa** [comment] 2017-10-31 04:38
Someone, who bought me a "coffee" today, should check his mailbox.

**Comment by PaulYmer111** [comment] 2017-10-31 06:02
hi sstativa, I am wondering where I can find a good café to buy you a coffee.

**Comment by sstativa** [comment] 2017-10-31 06:04
It's about donation button on Readme page :)

**Comment by PaulYmer111** [comment] 2017-11-01 08:23
hi sstativa, how far am I from the target of checking my mailbox ?........

**Comment by sstativa** [comment] 2017-11-01 11:08
Hmm...  I thought I replied to everyone. Are you sure it is not in your spam folder? Is your email bxxxx.lxxxx@xxxxt?

**Comment by H4rm10d** [comment] 2017-11-10 21:40
I know the idea is crowd funding, but how many "coffees" would it take me to get a "release candidate" version of it? (also a windows user)

**Comment by rarandom** [comment] 2017-11-18 21:21
Has this been fixed by MFC? I'm still seing this on videos from yesterday. Seeing as to how this issue is 20 days old, that would either mean that MFC is rather slow at fixing this (if they ever intend to), or I need to search for another cause for my particular issue...

**Comment by sstativa** [comment] 2017-11-20 12:05
I'm not sure they are gonna fix it at all. 

The next one is only my thoughts, I might be wrong.
I assume MFC changed the size of HLS "chunks", as results __ffmpeg__ starts dropping segments if it was too slow to download them ([example of the problem](https://github.com/soimort/you-get/issues/1270)). In some cases fast Internet helps to minimise the impact but not solves the problem.

Currently there are several possible solutions:
1) I'm kind of running "crowdfunding campaign", as soon as I reach the goal in 333 coffees, I'll release my rtmp version of mfc-node that has no issues with freezing.
2) Or you can search for customised version of mfc-node that uses __livestreamer__ instead of __ffmpeg__. Personally I did not try it, but based on the comments I've seen it does a pretty good job.
3) There is a still small chance that MFC will fixes the problem, but I doubt this.

**Comment by Photosounder** [comment] 2017-12-04 02:18
I tried both ffmpeg (from the command line) and livestreamer, ffmpeg always skipped segments, but livestreamer never drops anything, at least when I specify the maximum number of HLS segment threads (so you can't be late at downloading a segment like ffmpeg is because ffmpeg dumbly gets them one by one). Here's an example:
livestreamer.exe --hls-segment-threads 10 "hlsvariant://http://video813.myfreecams.com:1935/NxServer/ngrp:mfc_118156599.f4v_mobile/playlist.m3u8" best -o rec.avi

**Closed** 2018-01-29 00:50 UTC
